### PR TITLE
Add test function for the SE050

### PR DESCRIPTION
**Pull request by sosthene-nitrokey**
This PR adds a test function for the SE050 inside of the admin app.
This functionality is optional. It adds a new generic parameter for the Admin App that can either be an Se050 or the unit `()` type (default for backwards compatibility).

The SE050 test does:

- Return SE050 firmware version
- Return SE050 available memory
- Test most of the functionality and report progress, so that any we can know where errors happen.

The test starts with a factory-reset of the device.

### CODE REVIEW

**Comment by sosthene-nitrokey** [comment]
Corresponding nitropy update: https://github.com/Nitrokey/pynitrokey/pull/423

For some reason the test also causes a hard fault in the FIDO tests that follow when run with nitropy.

**Comment by sosthene-nitrokey** [comment]
The hard fault has been solved by https://github.com/Nitrokey/nitrokey-3-firmware/pull/332

**Review by robin-nitrokey — APPROVED** [review]
Looks good.  Maybe some code could be moved into a separate module to reduce the number of `cfg`s.

**Comment by sosthene-nitrokey** [comment]
> Looks good. Maybe some code could be moved into a separate module to reduce the number of `cfg`s.

Done

**Pull request merged**
